name: Build and Push Orion Image

on:
  push:
    branches: [ "main" ]    # 每次提交 main 分支时自动构建
  workflow_dispatch:        # 支持手动触发

env:
  IMAGE: lzycmcy/orion_my                 # 修改成你的 Docker Hub 仓库名
  BUILDER_ENDPOINT: docker.io/lzycmcy/lzymy   # 修改成你的 Build Cloud endpoint

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Buildx (Build Cloud)
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: ${{ env.BUILDER_ENDPOINT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug builders
        run: |
          docker buildx version
          docker buildx ls || true
          docker buildx inspect "${{ steps.buildx.outputs.name }}" || true

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max
